### ISSUE TITLE
timelog show 

### ISSUE THREAD

**Issue by flygare** [Lilja/timelog#24]
instead of timelog show logs

Also show current week

**Comment by Lilja** [comment]
Partly completed, it shows the current week. I agree `timelog log` was better than `timelog log project`, but does it make sense here?

**Comment by flygare** [comment]
is there anything else you can show?

**Comment by flygare** [comment]
How about timelog logs then? Similar to "docker logs" for example

**Comment by Lilja** [comment]
`list projects => project list`
`delete project => project delete`
`create project => project create`
`show logs => view`
log remains as is
