### ISSUE TITLE
View raw logs

### ISSUE THREAD

**Issue by Lilja** [Lilja/timelog#31]
For debugging? purposes I want to see raw logs. Are there any use case to see raw logs from a end-user perspective?

**Comment by flygare** [comment]
Do you mean the logs in ./config/timelog?

**Comment by Lilja** [comment]
Yes

**Comment by flygare** [comment]
Yes, atleast to edit, if I forgot to log one dat i have to open that file and edit it manually.

I also want to see daily hours for that week, I don't know if this is possible currently
